wielomed/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from custom_user import views as custom_userViews
from news import views as newsViews
from doctors import views as doctorViews
from diag_tests import views as diag_testViews
from links import views as linksViews

urlpatterns = [
    url(r'^$', newsViews.home, name='home'),
    url(r'^news/(?P<news_id>[0-9]+)/$', newsViews.newsPage, name='news'),
    url(r'^contact/', custom_userViews.contact, name='contact'),
    url(r'^news_add/', newsViews.newsEdit, name='news_add'),
    url(r'^schedule/', doctorViews.doctors_dates, name='doctors_dates'),
    # url(r'^diagnostics/', diag_testViews.diag_list, name='diagnostics'),
    url(r'^diagnostics_detail/(?P<diag_group_id>[0-9]+)/', diag_testViews.diag_detail, name='diagnostics_detail'),
    url(r'^diagnostics_list/', diag_testViews.diagnostics_list, name='diagnostics_list'),
    url(r'^links/', linksViews.links, name='links'),
    url(r'^news_list/', newsViews.newsList, name='news_list'),
    url(r'^news_edit/(?P<news_id>[0-9]+)/$', newsViews.newsEdit, name='news_edit'),
    url(r'^pref/', custom_userViews.userEdit, name='pref'),
    url(r'^sick/', custom_userViews.sickEdit, name='sick'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carusel/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from news.models import News

class Carusel(models.Model):

    title = models.CharField(verbose_name=_("Tytuł"), max_length=1000)
    subtitle = models.CharField(verbose_name=_("Podtytuł"), max_length=1000)

    link_CHOICES = (('U', 'URL'), ('N', 'News'), ('B', 'Brak'))
    link = models.CharField(max_length=1, choices=link_CHOICES, unique=False, null=False, default='B')
    url = models.URLField(verbose_name=_("Link Zewnętrzy"), null=True, blank=True)
    news = models.ForeignKey(News, null=True, blank=True)
    image = models.ImageField(verbose_name=_("Obrazek"), upload_to='slajd', blank=False)

    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Slajd"
        verbose_name_plural = "Slajdy"

doctors/models.py
# -*- coding: utf-8 -*-

# Create your models here.
# docktor
# data
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Doctor(models.Model):

    title = models.CharField(verbose_name=_("Tytuł"), max_length=1000)
    name = models.CharField(verbose_name=_("Imię"), max_length=1000)
    surname = models.CharField(verbose_name=_("Nazwisko"), max_length=1000)
    extras = models.TextField(verbose_name=_("Dodatkowe uwagi"), blank=True)
    urlop = models.BooleanField(verbose_name=_("Urlop"),blank=False, default=False)
    urlop_start = models.DateTimeField(verbose_name=_("Urlop początek"), default=None)
    urlop_end = models.DateTimeField(verbose_name=_("Urlop koniec"), default=None)

    # czas stworzenia i aktualizacji
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str("%s %s %s" % (self.title, self.name, self.surname))

    class Meta:
        verbose_name = _("Lekarz")
        verbose_name_plural = _("Lekarze")


class DoctorDates(models.Model):
    """
    dates for doctors
    """
    weekdays_CHOICES = (('PN', 'Poniedziałek'), ('WT', 'Wtorek'), ('SR', _('Środa')), ('CZ', 'Czwartek'), ('PT', 'Piątek'), ('SO', 'Sobota'), ('ND', 'Niedziela'))
    weekdays = models.CharField(verbose_name=_("Dzień tygodnia"), max_length=2, choices=weekdays_CHOICES,
                                   unique=False, blank=False)

    start_time = models.TimeField(verbose_name=_("Rozpoczęcie"),auto_now_add=False, auto_now=False, unique=False, blank=False)
    stop_time = models.TimeField(verbose_name=_("Zakończenie"),auto_now_add=False, auto_now=False, unique=False, blank=False)

    przychodnia_CHOICES = (('W', 'Wielogłowy'), ('I', 'Porąbka Iwkowska'))
    przychodnia = models.CharField(verbose_name=_("Przychodnia"), max_length=1, choices=przychodnia_CHOICES,
                                   unique=False, blank=False)

    wizyta_CHOICES = (('D', 'wizyta domowa'), ('P', 'wizyta w gabinecie'))
    wizyta = models.CharField(verbose_name=_("Rodzaj Wizyty"), max_length=1, choices=wizyta_CHOICES,
                                   unique=False, blank=False)

    extras = models.TextField(verbose_name=_("Dodatkowe uwagi"), blank=True)

    doctor = models.ForeignKey(Doctor)

    # czas stworzenia i aktualizacji
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    # def __str__(self):
    #     return str("%s %" % ())

    class Meta:
        verbose_name = _("Wizyta")
        verbose_name_plural = _("Wizyty")

links/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Link(models.Model):

    title = models.CharField(verbose_name=_("Temat"), max_length=1000)
    url = models.URLField(verbose_name=_("Link"))
    comment = models.TextField(verbose_name=_("Komentarz"),blank=True)
    priority = models.IntegerField(verbose_name=_("Priorytet"))
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _("Link")
        verbose_name_plural = _("Linki")

class HeadLink(models.Model):

    title = models.CharField(verbose_name=_("Etykieta"), max_length=24)
    url = models.URLField(verbose_name=_("Link"))
    show = models.BooleanField(verbose_name=_("Aktywny"), default=False)
    priority = models.IntegerField(verbose_name=_("Priorytet"))

    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _("LinkEtykieta")
        verbose_name_plural = _("LinkiEtykiety")

news/models.py
from django.db import models
from custom_user.models import Sickness
from django.utils.translation import ugettext_lazy as _


class News(models.Model):
    """
    Newsy z dodatkowymi parametrami dla oraniczenin wyswietlania i zawiadamiania szegolnych grup uzytkownikow
    """
    # dane newsa
    text = models.TextField(verbose_name=_("Tekst"), null=False)
    image = models.ImageField(verbose_name=_("Obrazek"), upload_to='news', blank=True)
    title = models.CharField(verbose_name=_("Tytuł"), max_length=50, unique=True, null=False,)
    subtitle = models.CharField(verbose_name=_("Podtytuł"), max_length=50, unique=False, blank=True,)
    # dodatkowe ograniczenia
    PLEC_CHOICES = (('M', 'Mezczyżna'), ('K', 'Kobieta'))
    plec = models.CharField(verbose_name=_("Płeć"), max_length=1, choices=PLEC_CHOICES, unique=False, blank=True)
    przychodnia_CHOICES = (('W', 'wielogłowy'), ('I', 'Iwkowa'))
    przychodnia = models.CharField(verbose_name=_("Przychodnia"), max_length=1, choices=przychodnia_CHOICES,
                                   unique=False, blank=True)
    data_urodzenia_max = models.DateField(verbose_name=_("Data najstarszego urodzenia"), auto_now=False,
                                          auto_now_add=False, blank=True, null=True)
    data_urodzenia_min = models.DateField(verbose_name=_("Data najmłodszego urodzenia"), auto_now=False,
                                          auto_now_add=False, blank=True, null=True)
    sickness = models.ForeignKey(Sickness, verbose_name=_("Choroba"), blank=True, null=True)

    # czas stworzenia i aktualizacji
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("Newsy")

news/forms.py
from __future__ import unicode_literals
from django import forms
from .models import News
from django.utils.translation import ugettext_lazy as _
from custom_user.models import Sickness
from datetimewidget.widgets import DateWidget
from floppyforms import ClearableFileInput


class ImageThumbnailFileInput(ClearableFileInput):
    """
    miniaturka obrazka dla panelu admina
    """
    template_name = 'floppyforms/image_thumbnail.html'


class NewsEditForm(forms.ModelForm):
    """
    formularz dla dodawania newsa
    """
    PLEC_CHOICES = (('M', 'Mezczyżna'), ('K', 'Kobieta'))
    plec = forms.ChoiceField(label=_("Płeć"), choices=PLEC_CHOICES, required=False)
    przychodnia_CHOICES = (('W', 'wielogłowy'), ('I', 'Iwkowa'))
    przychodnia = forms.ChoiceField(label=_("Przychodnia"), choices=przychodnia_CHOICES, required=False)
    data_urodzenia_max = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3), required=False)
    data_urodzenia_min = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3), required=False)
    text = forms.CharField(label=_("Tekst"), widget=forms.Textarea(attrs={'placeholder': 'Wpisz tekst'}), required=True)
    image = forms.ImageField(label=_("Obrazek"), widget=ImageThumbnailFileInput, required=False)
    title = forms.CharField(label=_('Tytuł'), required=True)
    subtitle = forms.CharField(label=_('Podtytuł'), required=False)
    sickness = forms.ModelChoiceField(label=_('Choroba'), queryset=Sickness.objects.all(), required=False)

    class Meta:
        model = News
        fields = ('plec', 'przychodnia', 'sickness', 'data_urodzenia_max', 'data_urodzenia_min', 'text',
                  'title', 'subtitle', 'image')

carusel/views.py
from django.shortcuts import render

# Create your views here.

links/views.py
from django.shortcuts import render
from .models import Link
# Create your views here.
def links(request):

    template = "links.html"
    # doctors_datest = []
    links = Link.objects.order_by('-priority')

    context = {
        'links':links,
    }
    # for doctors in doctors_datest:
    #     print(doctors['dates'].get_shirt_size_display())
    return render(request, template,context=context)

news/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.template import RequestContext

from .models import News
from .forms import NewsEditForm
from carusel.models import Carusel

def checkStaff(request):
    """
    spradza czy uzytkownik jest pracownikiem
    gdy nie jest odpowiedz to strona 404
    :param request:
    :return:
    """
    user = request.user
    if not user.is_staff:
        raise Http404


def home(request):
    """
    strona domowa
    newsy pobierane z bazy dlugosc tekstu okrojona do 50 slow
    :param request:
    :return:
    """
    template = 'home.html'

    news = News.objects.order_by('-timestamp')
    carousels = Carusel.objects.order_by('-timestamp')

    carusel_data = ['Zapraszamy od przychodni w Wielogłowach!', 'Zapraszamy do przychodni w Iwkowej!']

    context = {
        'carusel_data': carusel_data,
        'carousels': carousels,
        'news': news
    }

    return render(request, template, context=context, context_instance=RequestContext(request))


def newsPage(request, news_id):
    """
    strona z newsem
    :param request:
    :param news_id:id newsa
    :return:
    """
    template = 'news.html'
    news = get_object_or_404(News, id=news_id)

    context = {'news': news,
               }

    return render(request, template, context=context)


def newsEdit(request, news_id=None):
    """
    edycja lub dodanie newsa
    :param request:
    :param news_id:id edytowanego newsa
    :return:
    """
    checkStaff(request)

    template = 'news_add.html'
    if news_id:
        news = get_object_or_404(News, id=news_id)
    else:
        news = None

    form = NewsEditForm(request.POST or None, request.FILES or None, instance=news)
    if form.is_valid():
        form.save()
        return redirect('home')

    context = {'form': form, }

    return render(request, template, context=context)


def newsList(request):
    """
    panel do edycji newsow
    :param request:
    :return:
    """

    checkStaff(request)

    template = "news_list.html"

    to_delete = request.POST.getlist('delete_box')
    print(to_delete)
    if to_delete:
        News.objects.all().filter(id__in=to_delete).delete()

    news_objects = News.objects.values('id', 'title', 'timestamp').order_by('-timestamp')

    context = {'news_objects': news_objects,}
    return render(request, template,context=context)

templates/base.html
{% load staticfiles %}
{% load cookielaw_tags %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>


    {% include "head_meta.html" %}

    <title>{% block title %}Wielomed{% endblock %}</title>
    {% include "head_css.html" %}

    <!-- cookie law  -->
    <script src="{% static 'cookielaw/js/cookielaw.js' %}"></script>
    <style>

        {% block style %}

        {% endblock %}

    </style>

</head>
<!-- NAVBAR
================================================== -->
<body>
{% include "navbar.html" %}

<!-- Carousel
================================================== -->

{% block carusel %}{% endblock %}

<div class="container" style="margin-top: 100px">

    {% cookielaw_banner %}
    {% block content %}

    {% endblock %}

</div>
<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <!-- Three columns of text below the carousel -->

    <!--
    <div class="row">
      <div class="col-lg-4">
        <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>

    </div>
    -->


    <!-- START THE FEATURETTES -->

    {% block features %}

    {% endblock %}


    <!-- FOOTER -->
    <footer>
        <p class="pull-right"><a href="#">Na górę</a></p>
        <!--<p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>-->
    </footer>

</div><!-- /.container -->


<!-- Bootstrap core JavaSc
<div class="col-md-12"></div>ript
================================================== -->
<script>

</script>
{% include "javascript.html" %}

{% block js %}

{% endblock %}

</body>
</html>

templates/carusel.html
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="first-slide" src="{% static 'img/house1.jpg' %}" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
            {% block first-slide %}
            {% endblock %}
{#              <h1>Example headline.</h1>#}
{#              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>#}
{#              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>#}
        </div>
      </div>
    </div>
    <div class="item">
      <img class="second-slide img-responsive" src="{% static 'img/house2.jpg' %}" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Another example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="third-slide" src="{% static 'img/house3.jpg' %}" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>One more for good measure.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->

templates/contact.html
{% extends "base.html" %}
{% load i18n %}

<style>
    {% block style %}

        html { height: 100% }
    body { height: 100% }


.Flexible-container {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 30px;
    height: 0;
    overflow: hidden;
}

.Flexible-container .map-container,
.Flexible-container object,
.Flexible-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

    {% endblock %}

</style>
{% block content %}
<script src="https://maps.googleapis.com/maps/api/js"></script>


 <script>

      function init_map_Wieloglowy() {
		var var_location = new google.maps.LatLng(49.671750, 20.691112);

        var var_mapoptions = {
          center: var_location,
          zoom: 14
        };

		var var_marker = new google.maps.Marker({
			position: var_location,
            map: var_map,
			title:"asd"});

        var var_map = new google.maps.Map(document.getElementById("map-container-Wieloglowy"),
            var_mapoptions);

		var_marker.setMap(var_map);




      }



      google.maps.event.addDomListener(window, 'load', init_map_Wieloglowy);

    </script>
   <div class="row">
      <div id="map-outer" class="col-sm-12">
          <div id="address_Wieloglowy" class="col-sm-4">
            <h2>Przychodnia Wielogłowy</h2>
            <address>
            <strong>Niepubliczny Zakład Opieki Zdrowotnej WIELOMED</strong><br>
                ul. Wielogłowy, 45<br>
                33-311 Wielogłowy<br>
                <abbr>Nr tel:</abbr> +48 18 443 25 10
           </address>
          </div> <!-- /adress -->
       <div class="Flexible-container">
            <div class="map-container" id="map-container-Wieloglowy"></div>
       </div><!-- /Flexible-container -->
      </div> <!-- /map-outer -->
    </div> <!-- /row -->

<hr>

 <script>

      function init_map_Iwkowa() {
		var var_location = new google.maps.LatLng(49.797251, 20.596938);

        var var_mapoptions = {
          center: var_location,
          zoom: 14
        };

		var var_marker = new google.maps.Marker({
			position: var_location,
            map: var_map,
			title:"Venice"});

        var var_map = new google.maps.Map(document.getElementById("map-container-Iwkowa"),
            var_mapoptions);

		var_marker.setMap(var_map);

      }



      google.maps.event.addDomListener(window, 'load', init_map_Iwkowa);

    </script>
     <div class="row">
      <div id="map-outer" class="col-sm-12">
          <div id="address_Iwkowa" class="col-sm-4">
            <h2>Przychodnia Porąbka Iwkowska</h2>
            <address>
            <strong>Niepubliczny Zakład Opieki Zdrowotnej WIELOMED</strong><br>
                ul. Porąbka Iwkowska 109<br>
                Porąbka iwkowska 32-862<br>
                <abbr>Nr tel:</abbr> +48 14 684 42 15
           </address>
          </div> <!-- /adress -->
       <div class="Flexible-container">
            <div class="map-container" id="map-container-Iwkowa"></div>
       </div><!-- /Flexible-container -->
      </div> <!-- /map-outer -->
    </div> <!-- /row -->

    <hr>
{% endblock %}

templates/doctors_dates.html
{% extends 'base.html' %}
{% load staticfiles %}
{#{% load template_extras %}#}
{% block title %}
    {{ block.super }} | Dyżury
{% endblock %}
<style xmlns="http://www.w3.org/1999/html">
    {% block style %}
        i.fa {
        font-size:18px;
        }
        .fa.fa-hospital-o {
        color: #436d9a;
        }
        .fa.fa-home {
        color: #0caf00;
        }

    {% endblock %}
</style>

{% block features %}
    <div class="row">
        <div class="list-group">
            <a id="W-href" onclick="setDates('W')" class="list-group-item active col-md-2" style="cursor:pointer"><h4
                    class="list-group-item-heading">
                Wielogłowy</h4></a>
            <a id="I-href" onclick="setDates('I')" class="list-group-item col-md-2" style="cursor:pointer"><h4 class="list-group-item-heading">
                Porąbka Iwkowska</h4></a>
        </div>
    </div>
    <div id="W-tab" class="row">
        <table class="table table-hover ">
            <tbody>
            <thead>
            <tr>
                <th class="col-md-1 col-xs-2">Dzień</th>
                <th class="col-md-1 col-xs-1">Godziny</th>
                <th class="col-md-2 col-xs-1">Wizyta</th>
                <th class="col-md-2 col-xs-2">Uwagi</th>
            </tr>
            </thead>
            {% for dd in doctors_datest_W %}
                <tr class="info">
                    <td colspan="2">{{ dd.doctor }}</td>
                    <td colspan="3">{{ dd.doctor.extras }}</td>
                </tr>
                {% if dd.doctor.urlop %}
                <tr class="warning">
                    <td colspan="2" >Urlop</td>
                    <td colspan="1" ><i class="fa fa-plane" aria-hidden="true"></i>
Od {{ dd.doctor.urlop_start|date }} </td>
                    <td colspan="2" >Do {{ dd.doctor.urlop_end|date }}</td>
                </tr>

                {% else %}

                {% for date in dd.dates %}
                    <tr>
                        <td class="col-md-1 col-xs-2">{{ date.get_weekdays_display }}</td>
                        <td class="col-md-1">{{ date.start_time|time:"H:i" }}-{{ date.stop_time|time:"H:i" }}</td>
                        <td class="col-md-2">
                            {% ifequal date.wizyta "D" %}
                                <i class="fa fa-home" aria-hidden="true"></i>

                            {% else %}

                                <i class="fa fa-hospital-o" aria-hidden="true"></i>

                            {% endifequal %}
                            {{ date.get_wizyta_display }}
                        </td>
                        <td class="col-md-2">{{ date.extras }}</td>
                    </tr>

                {% endfor %}
                {% endif %}

            {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="I-tab" style="display: none;" class="row">
        <table class="table table-hover ">
            <tbody>
            <thead>
            <tr>
                <th class="col-md-1 col-xs-2">Dzień</th>
                <th class="col-md-1 col-xs-1">Godziny</th>
                <th class="col-md-2 col-xs-1">Wizyta</th>
                <th class="col-md-2 col-xs-2">Uwagi</th>
            </tr>
            </thead>
            {% for dd in doctors_datest_I %}
                <tr>
                    <td colspan="5" class="info">{{ dd.doctor }}</td>
                </tr>
                {% for date in dd.dates %}
                    <tr>
                        <td class="col-md-1 col-xs-2">{{ date.get_weekdays_display }}</td>
                        <td class="col-md-1">{{ date.start_time|time:"H:i" }}-{{ date.stop_time|time:"H:i" }}</td>
                        <td class="col-md-2">
                            {% ifequal date.wizyta "D" %}
                                <i class="fa fa-home" aria-hidden="true"></i>
                            {% else %}
                                <i class="fa fa-hospital-o" aria-hidden="true"></i>
                            {% endifequal %}
                            {{ date.get_wizyta_display }}
                        </td>
                        <td class="col-md-2">{{ date.extras }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}

            </tbody>
        </table>
    </div>



    <!-- /END THE FEATURETTES -->
{% endblock %}
{% block js %}

    <script>
        function setDates(name) {
            if (name === "I") {
                var no_name = "W";
            } else {

                var no_name = "I";
            }
            console.log(name.concat("-href"));
            console.log(no_name.concat("-href"));

            document.getElementById(name.concat("-href")).classList.add('active');
            document.getElementById(no_name.concat("-href")).classList.remove('active');
            document.getElementById(name.concat("-tab")).style.display = "block";
            document.getElementById(no_name.concat("-tab")).style.display = "none";

        }

    </script>
{% endblock %}
document.getElementById(name.concat("-href")).className += "active";
document.getElementById("MyElement").className = document.getElementById("MyElement").className.replace( /(?:^|\s)MyClass(?!\S)/g , '' )
document.getElementById(no_name.concat("-tab")').style.display='none'

templates/head_meta.html
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

templates/links.html
{% extends 'base.html' %}
{% load staticfiles %}
{#{% load template_extras %}#}
{% block title %}
    {{ block.super }} | Linki
{% endblock %}
<style>
    {% block style %}

    {% endblock %}
</style>

{% block features %}
    {% for link in links %}
     <div  class="row">
    <div class="col-md-5"><a href="{{ link.url }}"><h4>{{ link.title }}</h4></a></div>
    </div>
    {% empty %}
     <div  class="row">
    <div class="col-md-5"><h4>Chwilowy brak linków zapraszamy wktótce!</h4></div>
    </div>
    {% endfor %}


{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load staticfiles %}
{#{% load template_extras %}#}
{% block title %}
{{ block.super }} | {{ news.title }}
{% endblock %}
<style>
    {% block style %}

    {% endblock %}
</style>




{% block features %}

      <div class="row featurette">
        <div class="col-md-7 ">
        {% if request.user.is_staff %}
            <a href="{% url 'news_edit' news.id %}"><button id="zmien_btn" type="submit" class="btn btn-default">Zmień</button><span class="sr-only">(current)</span></a>
        {% endif %}
          <h2 class="featurette-heading"><div class="news_title">{{ news.title }}</div> {% if news.subtitle %}
           <span class="text-muted"><br>{{  news.subtitle }}</span>
          {% endif %}</h2>
          <p class="lead">{{ news.text }}</p>
        </div>
        <div class="col-md-5  ">
          <img class="featurette-image img-responsive center-block img-rounded" src="{% if news.image %}{{ news.image.url }}{% else %}{% static 'img/news_standard_img.jpg' %}{% endif %}"  alt="Generic placeholder image">
        </div>
      </div>
      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->
{% endblock %}